[package]
name = "adventure"
version = "0.1.0"
authors = ["Chris Laverdiere <cmlaverdiere@gmail.com>"]

[dependencies]
rand = "0.6.5"
clap = "2.33.0"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"

